create table users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    role varchar(32),
    github_username varchar(255),
    password_hash varchar(255),
    created_at timestamp not null
);

create table team (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255),
    created_at timestamp not null
);

create table project (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255),
    deadline date,
    github_repository_url varchar(255),
    status varchar(32),
    created_at timestamp not null,
    team_id bigint,
    constraint fk_project_team foreign key (team_id) references team(id)
);

create table task (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description varchar(255),
    status varchar(32),
    priority varchar(32),
    due_date date,
    assigned_user_id bigint,
    project_id bigint,
    completed_at timestamp,
    created_at timestamp not null,
    constraint fk_task_user foreign key (assigned_user_id) references users(id),
    constraint fk_task_project foreign key (project_id) references project(id)
);

create table document (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content clob,
    project_id bigint,
    created_by_id bigint,
    created_at timestamp not null,
    updated_at timestamp,
    constraint fk_document_project foreign key (project_id) references project(id),
    constraint fk_document_user foreign key (created_by_id) references users(id)
);

create table contribution (
    id bigint generated by default as identity primary key,
    project_id bigint,
    user_id bigint,
    commit_count integer not null,
    pull_request_count integer not null,
    files_changed integer not null,
    code_churn bigint not null,
    trivial_changes bigint not null,
    contribution_score double precision not null,
    analysis_date timestamp,
    constraint fk_contribution_project foreign key (project_id) references project(id),
    constraint fk_contribution_user foreign key (user_id) references users(id)
);

create table health_score (
    id bigint generated by default as identity primary key,
    project_id bigint,
    commit_trend double precision not null,
    task_completion_rate double precision not null,
    deadline_score double precision not null,
    health_score double precision not null,
    status varchar(32),
    calculated_at timestamp,
    constraint fk_health_project foreign key (project_id) references project(id)
);

create table team_members (
    user_id bigint not null,
    team_id bigint not null,
    primary key (user_id, team_id),
    constraint fk_team_members_user foreign key (user_id) references users(id),
    constraint fk_team_members_team foreign key (team_id) references team(id)
);

create index idx_task_project on task(project_id);
create index idx_contribution_project on contribution(project_id);
create index idx_health_project on health_score(project_id);
